parameters:

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true
    bind:
      $kernelRootDir: '%kernel.root_dir%'
      $directoryRepository: '%ibx_content_dto.directory_repository%'
      $directoryDto: '%ibx_content_dto.directory_dto%'
      $contentTypeGroups: '%ibx_content_dto.content_type_groups%'

  Kaliop\IbexaContentDto\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Kaliop\IbexaContentDto\Services\String\NamespaceCreator:
    autowire: true
    autoconfigure: true

  Kaliop\IbexaContentDto\Command:
    resource: '../../Command'
    autowire: true
    autoconfigure: true
    tags:
      - { name: console.command }