parameters:

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true
    bind: ~ 
      
  Kaliop\IbexaContentDto\Command:
    resource: '../../Command'
    autowire: true
    autoconfigure: true
    tags:
      - { name: console.command }